### ISSUE TITLE
Can't compile the example

### ISSUE THREAD

**Issue by rossviljoen** [cambridge-mlg/ms_cxx_graph_api_example#1]
Getting the following error:
```
[ 75%] Linking CXX executable cxx_example
/usr/bin/cmake -E cmake_link_script CMakeFiles/cxx_example.dir/link.txt --verbose=1
/usr/bin/c++  -std=c++17 -Wall -fPIC CMakeFiles/cxx_example.dir/main.cc.o -o cxx_example   -L/home/ross/mindspore-julia/mindspore/mindspore  -Wl,-rpath,/home/ross/mindspore-julia/ms_cxx_graph_api_example/build:/home/ross/mindspore-julia/mindspore/mindspore libcxx_graph_api.so -l_c_expression.cpython-39-x86_64-linux-gnu -lmindspore_gvar -lpython3.9 -lm -lsecurec -lstdc++ -ldl -lgcc_s -lpthread 
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToNc1hwc04(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToFracZc04(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToFracNz(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToNc1hwc0(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NcdhwToFracZ3D(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToFracZ(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NcdhwToNdc1hwc0(mindspore::trans::FormatArgs const&, void*)'
libcxx_graph_api.so: undefined reference to `mindspore::trans::NchwToC1hwncoc0(mindspore::trans::FormatArgs const&, void*)'
```

Using `mindspore v1.4.0`

**Comment by rossviljoen** [comment]
Some more details:

This is after compiling mindspore from source (and modifying `mindspore/ccsrc/CMakeLists.txt`) on a fresh Ubuntu 18.04 install using the automatic installation script from:
https://gitee.com/mindspore/docs/blob/master/install/mindspore_cpu_install_source_en.md

**Comment by rossviljoen** [comment]
compiles with mindspore v1.2.0
